# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
        types: [python]
      - id: end-of-file-fixer
        types: [python]
      # - id: check-yaml
      - id: check-added-large-files
        types: [python]
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.0
    hooks:
      - id: autoflake
        types: [python]
        args:
          - "--in-place"
          - "--expand-star-imports"
          - "--remove-all-unused-imports"
          - --exclude=__init__.py
          - "--remove-unused-variables"
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
        name: isort (python)
        # args:
        #   - --ls
  - repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3
        types: [python]
        args:
          - "--preview"
        #   - --config
        #   - .code_quality/pyproject_black.toml
  # - repo: https://github.com/asottile/dead
  #   rev: v1.5.0
  #   hooks:
  #     - id: dead
  #       types: [python]
  # - repo: https://github.com/PyCQA/bandit
  #   rev: 1.7.4
  #   hooks:
  #     - id: bandit
  #       types: [python]
  #       args:
  #         - -c
  #         - .code_quality\bandit.yaml
  #         - -o
  #         - .reports\bandit.log
